### ISSUE TITLE
kodi wayland fullscreen mode

### ISSUE THREAD

**Issue by fleixi** [pkerling/xbmc#36]
your wayland fork has the same issue as Kellermanns  fork with fullscreen in gnome

See the issue here https://github.com/MaxKellermann/xbmc/issues/5

**Comment by fleixi** [comment]
sorry missed the guidelines for contributing

**Comment by yol** [comment]
Sorry, those are leftovers from the main Kodi repository! I've deleted them. It is perfectly valid to open bug tickets here. Please do not open a trac ticket since trac is unrelated to the Wayland fork.

So to solve your issue: Please post a [full debug log](http://kodi.wiki/view/Log_file/Easy) and upload a screenshot if possible.

**Comment by yol** [comment]
Aditionally, it might really help if you start Kodi with `WAYLAND_DEBUG=1` (environment variable) set and post the output. Also please post output of `gnome-shell --version`.

**Comment by yol** [comment]
Closing this for lack of reply and because it is probably a mutter bug.

See: https://github.com/mpv-player/mpv/issues/3935 https://bugzilla.gnome.org/show_bug.cgi?id=776428

Feel free to reopen if there is any new information.
